# [START runtime]
runtime: nodejs
env: flex
service: web-client

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:

env_variables:
  NODE_ENV: "production"
# [END runtime]

# [START skip files]
skip_files:
- node_modules/
# [END skip files]

# [START health checks]
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
# [END health checks]