apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: neo4j-backup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never      
          volumes:
          - name: backupdir-neo4j
            persistentVolumeClaim:
              claimName: backupdir-neo4j
          - name: neo4j-cluster
            secret:
              secretName: neo4j-cluster
          containers:
          - name: neo4j-backup
            image: "us.gcr.io/opit-193719/neo4j-image"
            env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: neo4jServiceIP
            volumeMounts:
            - name: backupdir-neo4j
              mountPath: /tmp
            - name: neo4j-cluster
              mountPath: "/etc/neo4j/secrets"
              readOnly: false            
            command:
            - "/bin/bash"
            - "-ecx"
            - |
              export NEO4J_dbms_connectors_default__advertised__address=$(hostname -f)
              export NEO4J_dbms_backup_address=$(hostname -f):6362
              export NEO4J_causal__clustering_discovery__advertised__address=$(hostname -f):5000
              export NEO4J_causal__clustering_transaction__advertised__address=$(hostname -f):6000
              export NEO4J_causal__clustering_raft__advertised__address=$(hostname -f):7000
              exec /docker-entrypoint.sh "backup"