apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: neo4j-backup
spec:
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: backupdir-neo4j
            persistentVolumeClaim:
              claimName: backupdir-neo4j
          - name: key
            secret:
              secretName: copy-neo4j-backup
          containers:
          - name: copy-backup
            image: "us.gcr.io/opit-193719/gcloud-image:latest"
            env:
            - name: BACKUP_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: neo4j-backup-location
            volumeMounts:
            - name: backupdir-neo4j
              mountPath: /tmp
            - name: key
              mountPath: /var/secrets/
              readOnly: true
            command: 
              - "/bin/bash"
              - "-ecx"
              - |
                exec /docker-entrypoint.sh
