# [START runtime]
runtime: node
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:

env_variables:
# [END runtime]

# [START handlers]
handlers:
 - url: /
   static_files: public/index.html
   upload: public/index.html

 - url: /(.*)
   static_files: public/\1
   upload: public/(.*)
# [END handlers]

# [START skip files]
skip_files:
- src/
- static/
- node_modules/
- .cache/
- blog/
# [END skip files]

# [START health checks]
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
# [END health checks]