apiVersion: v1
kind: Service
metadata:
  name: client-api
  labels:
    app: client-api  
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"client-api-tls":"HTTPS"}'
spec:
  selector:
    app: client-api
  ports:
  - name: client-api-tls
    protocol: TCP
    port: 443
    targetPort: 8443
  type: NodePort