apiVersion: v1
kind: Service
metadata:
  name: neo4j-load-balancer
  labels:
    app: neo4j
    component: core
spec:
  selector:
    app: neo4j
    component: core
  clusterIP: 10.59.245.198
  type: LoadBalancer
  # loadBalancerIP: 35.241.55.162 # dev-ingress static ip
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 7473
      targetPort: 7473
      name: https
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 6362
      targetPort: 6362
      name: backup