apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: neo4j-core
spec:
  serviceName: neo4j
  replicas: 3
  podManagementPolicy: "Parallel"
  updateStrategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: neo4j
        component: core
    spec:
      volumes:
      - name: neo4j-cluster
        secret:
          secretName: neo4j-cluster
      containers:
      - name: neo4j
        image: "us.gcr.io/opit-193719/dev-neo4j-image"
        imagePullPolicy: "Always"
        env:
          - name: NEO4J_dbms_mode
            value: CORE
          - name: NUMBER_OF_CORES
            value: "3"
          - name: NEO4J_causal__clustering_discovery__type
            value: DNS
          - name: NEO4J_causal__clustering_initial__discovery__members
            value: "neo4j.default.svc.cluster.local:5000"
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
          - name: NEO4J_dbms_security_causal__clustering__status__auth__enabled
            value: "false"
          - name: NEO4J_com_graphaware_module_ES_uri
            valueFrom:
              secretKeyRef:
                name: client-api-elastic-auth
                key: uri
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            export NEO4J_dbms_connectors_default__advertised__address=$(hostname -f)
            export NEO4J_causal__clustering_discovery__advertised__address=$(hostname -f):5000
            export NEO4J_causal__clustering_transaction__advertised__address=$(hostname -f):6000
            export NEO4J_causal__clustering_raft__advertised__address=$(hostname -f):7000
            exec /docker-entrypoint.sh "neo4j"
        ports:
        - containerPort: 5000
          name: discovery
        - containerPort: 7000
          name: raft
        - containerPort: 6000
          name: tx
        - containerPort: 7474
          name: browser
        - containerPort: 7473
          name: https
        - containerPort: 7687
          name: bolt
        - containerPort: 6362
          name: backup
        volumeMounts:
        - name: datadir
          mountPath: "/data"
        - name: neo4j-cluster
          mountPath: "/etc/neo4j/secrets"
          readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard"
        resources:
          requests:
            storage: "10Gi"


            