apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: api-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: api
    spec:
      containers:
      - name: api
        image: gcr.io/opit-193719/graph-api:latest
        ports:
        - containerPort: 8080