kind: Service
apiVersion: v1
metadata:
  name: graph-external-service
spec:
  selector:
    app: neo4j
  ports:
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
  type: LoadBalancer
  