apiVersion: v1
kind: Service
metadata:
  name: neo4j-node-port
  labels:
    app: neo4j
    component: core
spec:
  clusterIP: 10.59.247.100
  selector:
    app: neo4j
    component: core
  type: NodePort
  ports:
    - port: 7474
      targetPort: 7474
      name: browser
    - port: 7473
      targetPort: 7473
      name: https
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 6362
      targetPort: 6362
      name: backup