# [START runtime]
runtime: nodejs
env: flex
service: client-api

manual_scaling:
  instances: 1
  
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: opit-193719:us-central1:mysql-test

env_variables:
  SQL_USER: root
  SQL_PASSWORD: ""
  SQL_DATABASE: test
  INSTANCE_CONNECTION_NAME: opit-193719:us-central1:mysql-test
  NODE_ENV: "production"
# [END runtime]

