apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
      - name: client-api
        image: us.gcr.io/opit-193719/client-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8000