# [START runtime]
runtime: nodejs
env: flex
service: client-api-dev

manual_scaling:
  instances: 1
  
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  NODE_ENV: "development"
  NEO4J_ENDPOINT: "bolt+routing://35.197.60.182:7687"
  NEO4J_USER: "neo4j"
  NEO4J_PASSWORD: "mz6bJV6YC9irutUo"
# [END runtime]

