apiVersion: v1
kind: Service
metadata:
  name: client-api
  labels:
    app: client-api
spec:
  clusterIP: 10.59.246.131
  selector:
    app: client-api
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort