# [START runtime]
runtime: python27
threadsafe: true
service: dev

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
# [END runtime]

# [START handlers]
handlers:
  - url: /service-worker\.js
    static_files: build/service-worker.js
    upload: build/service-worker\.js

  - url: /asset-manifest\.json
    static_files: build/asset-manifest.json
    upload: build/asset-manifest\.json

  - url: /manifest\.json
    static_files: build/manifest.json
    upload: build/manifest\.json

  - url: /favicon\.ico
    static_files: build/favicon.ico
    upload: build/favicon\.ico
  
  - url: /(.*)static/(.*\.(css|js|map))$
    static_files: build/static/\2
    upload: build/static/.*\.(css|js|map)$

  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
# [END handlers]

# [START skip files]
skip_files:
- src/
- public/
- node_modules/
# [END skip files]

# [START health checks]
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
# [END health checks]